### ISSUE TITLE
python 36 support

### ISSUE THREAD

**Issue by sannykr** [conda-forge/pytest-django-feedstock#9]
Python 36 files are not available on conda-forge. Could you please rerender the feedstock. I think rerendering the feedstock will be helpful, otherwise there could be some other way.

**Comment by sannykr** [comment]
@ocefpaf : following up. 
I can't see python 36 files on anaconda.org. Is it possible to make this package "noarch"?

**Comment by ocefpaf** [comment]
If you find a way to fix https://github.com/conda-forge/pytest-django-feedstock/pull/7#issuecomment-328927902 we can do that. Closing this as a duplicate of #7, let;s keep this discussion there to avoid noise.
